#!/usr/bin/env node

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(scriptDirectory, "../..");
const aiDirectory = join(repositoryRoot, ".ai");
// Cursor loads `.claude/skills` as a documented compatibility location and it is
// Claude Code's native location, so one tree serves both clients. Generating a
// second `.cursor/skills` copy makes each shortcut appear twice in Cursor.
const sourceDirectories = ["commands", "workflows"];
const skillRoots = [".claude/skills"];
const checkOnly = process.argv.includes("--check");

function markdownFiles(directory) {
  const absoluteDirectory = join(aiDirectory, directory);
  if (!existsSync(absoluteDirectory)) {
    return [];
  }

  return readdirSync(absoluteDirectory)
    .filter((file) => file.endsWith(".md"))
    .sort()
    .map((file) => ({
      name: file.slice(0, -3),
      source: `.ai/${directory}/${file}`,
      content: readFileSync(join(absoluteDirectory, file), "utf8"),
    }));
}

function descriptionFor(command) {
  const lines = command.content
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"));
  const description = lines[0]?.replace(/^[-*]\s*/, "") ?? `Run /${command.name}.`;
  return description.replace(/["\n\r]/g, "").slice(0, 160);
}

function validate(commands) {
  const errors = [];
  const seen = new Map();

  for (const command of commands) {
    if (!/^[a-z0-9-]+$/.test(command.name)) {
      errors.push(`${command.source}: name must use lowercase letters, numbers, or hyphens`);
    }

    const expectedHeading = `# /${command.name}`;
    if (!command.content.startsWith(expectedHeading)) {
      errors.push(`${command.source}: first line must be "${expectedHeading}"`);
    }

    const existing = seen.get(command.name);
    if (existing) {
      errors.push(`Duplicate /${command.name}: ${existing} and ${command.source}`);
    }
    seen.set(command.name, command.source);
  }

  const shortcutIndex = readFileSync(join(aiDirectory, "shortcuts.md"), "utf8");
  const indexedNames = new Set(
    [...shortcutIndex.matchAll(/^\| `\/([a-z0-9-]+)` \|/gm)].map((match) => match[1]),
  );

  for (const command of commands) {
    if (!indexedNames.has(command.name)) {
      errors.push(`${command.source}: /${command.name} is missing from .ai/shortcuts.md`);
    }
  }

  for (const indexedName of indexedNames) {
    if (!seen.has(indexedName)) {
      errors.push(`.ai/shortcuts.md: /${indexedName} has no canonical definition`);
    }
  }

  if (errors.length > 0) {
    throw new Error(errors.join("\n"));
  }
}

function skillContent(command) {
  return `---
name: ${command.name}
description: "${descriptionFor(command)}"
disable-model-invocation: true
---

${command.content.trim()}

---

Apply \`.ai/router.md\` and the repository rules in \`CLAUDE.md\`. For code or
product changes, use \`docs/PROJECT_SPEC.md\` and \`docs/DEVELOPMENT_PLAN.md\` as
the source of truth. If instructions conflict, repository-specific rules win.

Generated from \`${command.source}\`. Edit that file, then run
\`node .ai/scripts/sync-skills.mjs\`.
`;
}

function commandIndex(commands) {
  const entries = commands
    .map((command) => `- \`${command.source}\` — \`/${command.name}\``)
    .join("\n");

  return `# Command Files

Generated by \`node .ai/scripts/sync-skills.mjs\`. Do not edit this index by hand.

${entries}
`;
}

function expectedFiles(commands) {
  const files = new Map();
  files.set(".ai/COMMANDS.md", commandIndex(commands));

  for (const skillRoot of skillRoots) {
    for (const command of commands) {
      files.set(`${skillRoot}/${command.name}/SKILL.md`, skillContent(command));
    }
  }

  return files;
}

function checkFiles(files) {
  const errors = [];

  for (const [path, expected] of files) {
    const absolutePath = join(repositoryRoot, path);
    if (!existsSync(absolutePath)) {
      errors.push(`Missing generated file: ${path}`);
      continue;
    }

    if (readFileSync(absolutePath, "utf8") !== expected) {
      errors.push(`Out-of-date generated file: ${path}`);
    }
  }

  for (const skillRoot of skillRoots) {
    const absoluteRoot = join(repositoryRoot, skillRoot);
    if (!existsSync(absoluteRoot)) {
      continue;
    }

    const expectedNames = new Set(
      [...files.keys()]
        .filter((path) => path.startsWith(`${skillRoot}/`))
        .map((path) => path.split("/")[2]),
    );

    for (const entry of readdirSync(absoluteRoot, { withFileTypes: true })) {
      if (entry.isDirectory() && !expectedNames.has(entry.name)) {
        errors.push(`Unexpected generated skill: ${relative(repositoryRoot, join(absoluteRoot, entry.name))}`);
      }
    }
  }

  if (errors.length > 0) {
    throw new Error(errors.join("\n"));
  }
}

function writeFiles(files) {
  for (const skillRoot of skillRoots) {
    rmSync(join(repositoryRoot, skillRoot), { recursive: true, force: true });
  }

  for (const [path, content] of files) {
    const absolutePath = join(repositoryRoot, path);
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, content);
  }
}

const commands = sourceDirectories.flatMap(markdownFiles);
validate(commands);
const files = expectedFiles(commands);

if (checkOnly) {
  checkFiles(files);
  console.log(`Validated ${commands.length} shortcuts in ${skillRoots.join(", ")}.`);
} else {
  writeFiles(files);
  console.log(`Generated ${commands.length} skills in ${skillRoots.join(", ")}.`);
}
